# This file was generated by GoReleaser. DO NOT EDIT.
cask "bohurupee" do
  version "0.5.5"

  on_macos do
    on_arm do
      sha256 "976db0ded50f8175db35a2f30c47d4d19613d9444c95a93be25f641afac9f44f"
      url "https://github.com/milon/bohurupee/releases/download/v#{version}/bohurupee_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "12fe98ad2308641c39992a818161952076e5d96dd1aa8cbf0646e011f8b226fb"
      url "https://github.com/milon/bohurupee/releases/download/v#{version}/bohurupee_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "fd4cfb50f187d494a617e502404ca09b2c5f364339421fc619ca4599b7ac686e"
      url "https://github.com/milon/bohurupee/releases/download/v#{version}/bohurupee_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3ebcd2319ccf3338fddcd8d74e0c4cf6718ec1011fcacf069236c16baaac78cb"
      url "https://github.com/milon/bohurupee/releases/download/v#{version}/bohurupee_#{version}_linux_amd64.tar.gz"
    end
  end

  name "bohurupee"
  desc "Local fake identity provider for OAuth and OIDC development. DEV ONLY."
  homepage "https://github.com/milon/bohurupee"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bohurupee"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bohurupee"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Bohurupee is a local fake identity provider. DEV ONLY. It listens on 127.0.0.1:4190.
  EOS
end
