# This file was generated by GoReleaser. DO NOT EDIT.
cask "bohurupee" do
  version "0.5.0"

  on_macos do
    on_arm do
      sha256 "6acbe74e9e75d948f658a3e156f071779f92977a6a76353ef869ca519537e580"
      url "https://github.com/milon/bohurupee/releases/download/v#{version}/bohurupee_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "6642c7209ce133f989be3199c871c0e5b89dd800083af0af4067de3b7b39d0c2"
      url "https://github.com/milon/bohurupee/releases/download/v#{version}/bohurupee_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "956b4fb041245809fede11df9f98eeb6fee9efc03de190725922178b4bcdcf65"
      url "https://github.com/milon/bohurupee/releases/download/v#{version}/bohurupee_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8088544553dcc2aab9e1dcd5a812d5cdd595e7ded6834fdc1e096e33d807979e"
      url "https://github.com/milon/bohurupee/releases/download/v#{version}/bohurupee_#{version}_linux_amd64.tar.gz"
    end
  end

  name "bohurupee"
  desc "Local fake identity provider for OAuth and OIDC development. DEV ONLY."
  homepage "https://github.com/milon/bohurupee"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bohurupee"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bohurupee"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Bohurupee is a local fake identity provider. DEV ONLY. It listens on 127.0.0.1:4190.
  EOS
end
