# This file was generated by GoReleaser. DO NOT EDIT.
cask "bohurupee" do
  version "0.5.1"

  on_macos do
    on_arm do
      sha256 "8859c8c0f0cfa6300b04fafc16f4a18ed68f2bd450572cba771e5c8703baa369"
      url "https://github.com/milon/bohurupee/releases/download/v#{version}/bohurupee_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3b05b663317f215a0861f133c5fb7a1d608c8884a3a3775f55fc0ea6b99866b1"
      url "https://github.com/milon/bohurupee/releases/download/v#{version}/bohurupee_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3c57bd10c8160430ce28cde112a882b67cd90bc7716b9570be0bdc131651879c"
      url "https://github.com/milon/bohurupee/releases/download/v#{version}/bohurupee_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fe312580c16cdc7613c122e684c580c6f629c591de48f2f1145a5eb64ba43fe3"
      url "https://github.com/milon/bohurupee/releases/download/v#{version}/bohurupee_#{version}_linux_amd64.tar.gz"
    end
  end

  name "bohurupee"
  desc "Local fake identity provider for OAuth and OIDC development. DEV ONLY."
  homepage "https://github.com/milon/bohurupee"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bohurupee"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bohurupee"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Bohurupee is a local fake identity provider. DEV ONLY. It listens on 127.0.0.1:4190.
  EOS
end
